### ISSUE TITLE
Anvil repair material for copper and flint tools

### ISSUE THREAD

**Issue by DentedLeft** [RandomMcSomethin/randoms-early-progression#1]
Would it be possible to make it so that flint and copper tools are repairable by their materials in the anvil?  Currently flint tools are repairable by wood and copper tools are repairable by cobblestone.

I appreciate your mod! Great work!
![2023-09-15_12 12 33](https://github.com/RandomMcSomethin/randoms-early-progression/assets/101304554/be74b5f3-9ffb-4273-91e0-ad8e77cfab60)
![2023-09-15_12 14 16](https://github.com/RandomMcSomethin/randoms-early-progression/assets/101304554/a6476e81-d27d-425e-8004-47d2e5ea749d)

**Comment by RandomMcSomethin** [comment]
Fixed in 1.2.0.
